# yaml configuration file for silence-monitor.py
# mqtt broker configuration
#
mqtt:
  mqtt_broker: 10.1.10.183
  mqtt_port: 1883
  mqtt_username: 'iotuser'
  mqtt_password: '3ERv5V1l'
  mqtt_topic_prefix: radio-stations
  log_level: INFO # INFO or DEBUG
  device_unique_id: stations
  discovery_topic: homeassistant
#
# station configuration
#
stations:
  - station_name: mystic_dreams
    station_url: http://mysticice.i234.me:8200/radio.mp3
    silence_threshold: -50.0  # in dB
    silence_duration: 15  # in seconds
    chunk_size: 8192  # Optional, bytes
    debounce_time: 5  # Optional, seconds to confirm silence

  - station_name: ambient_crystals
    station_url: http://mysticice.i234.me:8210/radio.mp3
    silence_threshold: -48.0
    silence_duration: 10
    chunk_size: 8192  # Optional, bytes
    debounce_time: 5  # Optional, seconds to confirm silence

  - station_name: christmas_music
    station_url: http://mysticice.i234.me:8220/radio.mp3
    silence_threshold: -45.0
    silence_duration: 20
    chunk_size: 8192  # Optional, bytes
    debounce_time: 5  # Optional, seconds to confirm silence
